CREATE DATABASE chirpy;
USE chirpy;

CREATE TABLE `chirps` (

  -- TABLE CODE TO GO HERE
  id INT NOT NULL AUTO_INCREMENT,
  author VARCHAR(50) NOT NULL,
  chirp VARCHAR(255) NOT NULL,
  timedate DATETIME DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
  PRIMARY KEY (id)

);